LaserTron: Bike Class Reference
Bike Class Reference
#include <Bike.h>
Public Types
enum Base4Direction { Down, Right, Up, Left }
Public Member Functions
Bike (BikeWall *wall, ofVec2f startPos, Base4Direction startDir, ofColor color)
~Bike ()
void Update (ofxIlda::Frame *frame)
void Respawn (ofVec2f startPos, Base4Direction startDir)
void TurnCallback (bool left)
void TurnCallback (int idx)
ofVec2f getPostition ()
ofRectangle getHitBox ()
void Kill ()
Private Member Functions
void Spawn (ofVec2f startPos, Base4Direction startDir)
void Turn (bool Left)
void SetDirection (Base4Direction d)
Private Attributes
BikeWall * Wall
The wall object the path of the bike is written to.
ofVec2f Position
The current position of the bike in normalized coordinates.
ofVec2f Direction
The current velocity of the bike represented as a vector.
Base4Direction _Direction
The current cardinal direction of the bike.
float Speed = 0.005
The speed of the bike (the velocity is calculated based on this)
bool alive = false
The state of the bike (alive or dead)
ofRectangle Hitbox
The hitbox of the bike.
Detailed Description
Class representing a Player on the playfield. Contains and updates the status, and the transform of the player
Definition at line 10 of file Bike.h.
Member Enumeration Documentation
Base4Direction
enum Bike::Base4Direction
Cardinal direction
Enumerator
Down
Right
Up
Left
Definition at line 17 of file Bike.h.
Constructor & Destructor Documentation
Bike()
Bike::Bike (BikeWall * wall, ofVec2f startPos, Base4Direction startDir, ofColor color)
Creates a new Bike and places it on the playfield
Parameters
wall The wall object the path of the bike is written to
startPos The starting position of the bike in normalized space
startDir The starting cardinal direction of the bike
color The color of the bike (not implemented)
Definition at line 3 of file Bike.cpp.
References Spawn(), and Wall.
~Bike()
Bike::~Bike ()
Definition at line 9 of file Bike.cpp.
Member Function Documentation
getHitBox()
ofRectangle Bike::getHitBox ()
Returns the rectangle where the collision of the bike is detected as an AABB.
Returns
The hitbox of the bike
Definition at line 69 of file Bike.cpp.
References Hitbox.
getPostition()
ofVec2f Bike::getPostition ()
Returns
The normalized position of the bike on the playfield
Definition at line 64 of file Bike.cpp.
References Position.
Kill()
void Bike::Kill ()
Kills the bike removing it from the playfield. Sets the state of the bike to dead, and clears its walls
Definition at line 74 of file Bike.cpp.
References alive, BikeWall::Clear(), Hitbox, and Wall.
Respawn()
void Bike::Respawn (ofVec2f startPos, Base4Direction startDir)
Resets the position, direction, hitbox, and state of the bike. Clears the walls.
Parameters
startPos The position the bike resets to in normalized space.
startDir The cardinal direction the bike resets to.
Definition at line 42 of file Bike.cpp.
References Spawn().
SetDirection()
void Bike::SetDirection (Base4Direction d) private
Sets the velocity of the bike based on cardinal directions
Parameters
d The cardinal direction to turn towards.
Definition at line 83 of file Bike.cpp.
References _Direction, Direction, Down, Left, Right, and Up.
Referenced by Spawn(), and Turn().
Spawn()
void Bike::Spawn (ofVec2f startPos, Base4Direction startDir) private
Private member for spawning.
Parameters
startPos
startDir
Definition at line 22 of file Bike.cpp.
References BikeWall::AddNewLine(), alive, BikeWall::Clear(), Direction, Hitbox, Position, SetDirection(), Speed, and Wall.
Referenced by Bike(), and Respawn().
Turn()
void Bike::Turn (bool Left) private
Private member for turning.
Parameters
Left
Definition at line 35 of file Bike.cpp.
References _Direction, BikeWall::AddNewLine(), Position, SetDirection(), and Wall.
Referenced by TurnCallback().
TurnCallback() [1/2]
void Bike::TurnCallback (bool left)
PI Turns the bike to the left or right based on param.
Parameters
left If true, the bike turns to the left, otherwise to the right.
Definition at line 48 of file Bike.cpp.
References alive, and Turn().
Referenced by Player::ExecuteInput(), and Player::ProcessInput().
TurnCallback() [2/2]
void Bike::TurnCallback (int idx)
WIN Turns the bike to the specified direction.
Parameters
idx The direction of the bike (0-3: Up, Left, Down, Right)
Definition at line 55 of file Bike.cpp.
References _Direction, alive, and Turn().
Update()
void Bike::Update (ofxIlda::Frame * frame)
Updates the position of the bike based on the velocity of it. Also extends the wall, and updates the hitbox of the bike.
Parameters
frame (not used)
Definition at line 13 of file Bike.cpp.
References alive, Direction, BikeWall::ExtendLast(), Hitbox, Position, Speed, and Wall.
Member Data Documentation
_Direction
Base4Direction Bike::_Direction private
The current cardinal direction of the bike.
Definition at line 78 of file Bike.h.
Referenced by SetDirection(), Turn(), and TurnCallback().
alive
bool Bike::alive = false private
The state of the bike (alive or dead)
Definition at line 81 of file Bike.h.
Referenced by Kill(), Spawn(), TurnCallback(), and Update().
Direction
ofVec2f Bike::Direction private
The current velocity of the bike represented as a vector.
Definition at line 77 of file Bike.h.
Referenced by SetDirection(), Spawn(), and Update().
Hitbox
ofRectangle Bike::Hitbox private
The hitbox of the bike.
Definition at line 83 of file Bike.h.
Referenced by getHitBox(), Kill(), Spawn(), and Update().
Position
ofVec2f Bike::Position private
The current position of the bike in normalized coordinates.
Definition at line 76 of file Bike.h.
Referenced by getPostition(), Spawn(), Turn(), and Update().
Speed
float Bike::Speed = 0.005 private
The speed of the bike (the velocity is calculated based on this)
Definition at line 80 of file Bike.h.
Referenced by Spawn(), and Update().
Wall
BikeWall* Bike::Wall private
The wall object the path of the bike is written to.
Definition at line 75 of file Bike.h.
Referenced by Bike(), Kill(), Spawn(), Turn(), and Update().
The documentation for this class was generated from the following files:
D:/PROG/CPP/LaserTronGIT/LaserTron/src/Bike.h
D:/PROG/CPP/LaserTronGIT/LaserTron/src/Bike.cpp