LaserTron: ofApp Class Reference
ofApp Class Reference
#include <ofApp.h>
Public Member Functions
void setup ()
void update ()
void draw ()
void exit ()
void keyPressed (int key)
void keyReleased (int key)
void mouseMoved (int x, int y)
void mouseDragged (int x, int y, int button)
void mousePressed (int x, int y, int button)
void mouseReleased (int x, int y, int button)
void mouseEntered (int x, int y)
void mouseExited (int x, int y)
void windowResized (int w, int h)
void dragEvent (ofDragInfo dragInfo)
void gotMessage (ofMessage msg)
Public Attributes
ofxEtherdream * ED
GameThread * Game
ofxIlda::Frame frame
bool lastRestart = false
int restartPin = 15
int framePerUpdate = 2
int currentFrame = 0
Detailed Description
We use this to interface with ofx, and to create the GameThread and the Etherdream
Definition at line 13 of file ofApp.h.
Member Function Documentation
dragEvent()
void ofApp::dragEvent (ofDragInfo dragInfo)
Definition at line 106 of file ofApp.cpp.
draw()
void ofApp::draw ()
Definition at line 34 of file ofApp.cpp.
References GameThread::Draw(), Game, and GameThread::SendData().
exit()
void ofApp::exit ()
Definition at line 46 of file ofApp.cpp.
References WiringPi::clear().
gotMessage()
void ofApp::gotMessage (ofMessage msg)
Definition at line 101 of file ofApp.cpp.
keyPressed()
void ofApp::keyPressed (int key)
Definition at line 52 of file ofApp.cpp.
References Game, GameThread::QueueInput(), and GameThread::Restart().
keyReleased()
void ofApp::keyReleased (int key)
Definition at line 61 of file ofApp.cpp.
mouseDragged()
void ofApp::mouseDragged (int x, int y, int button)
Definition at line 71 of file ofApp.cpp.
mouseEntered()
void ofApp::mouseEntered (int x, int y)
Definition at line 86 of file ofApp.cpp.
mouseExited()
void ofApp::mouseExited (int x, int y)
Definition at line 91 of file ofApp.cpp.
mouseMoved()
void ofApp::mouseMoved (int x, int y)
Definition at line 66 of file ofApp.cpp.
mousePressed()
void ofApp::mousePressed (int x, int y, int button)
Definition at line 76 of file ofApp.cpp.
mouseReleased()
void ofApp::mouseReleased (int x, int y, int button)
Definition at line 81 of file ofApp.cpp.
setup()
void ofApp::setup ()
Definition at line 4 of file ofApp.cpp.
References ED, Game, WiringPi::INPUT, WiringPi::pinMode(), and restartPin.
update()
void ofApp::update ()
Definition at line 18 of file ofApp.cpp.
References WiringPi::digitalRead(), Game, WiringPi::HIGH, lastRestart, GameThread::Restart(), and restartPin.
windowResized()
void ofApp::windowResized (int w, int h)
Definition at line 96 of file ofApp.cpp.
Member Data Documentation
currentFrame
int ofApp::currentFrame = 0
Definition at line 43 of file ofApp.h.
ED
ofxEtherdream* ofApp::ED
Definition at line 32 of file ofApp.h.
Referenced by setup().
frame
ofxIlda::Frame ofApp::frame
Definition at line 35 of file ofApp.h.
framePerUpdate
int ofApp::framePerUpdate = 2
Definition at line 42 of file ofApp.h.
Game
GameThread* ofApp::Game
Definition at line 34 of file ofApp.h.
Referenced by draw(), keyPressed(), setup(), and update().
lastRestart
bool ofApp::lastRestart = false
Definition at line 38 of file ofApp.h.
Referenced by update().
restartPin
int ofApp::restartPin = 15
Definition at line 39 of file ofApp.h.
Referenced by setup(), and update().
The documentation for this class was generated from the following files:
D:/PROG/CPP/LaserTronGIT/LaserTron/src/ofApp.h
D:/PROG/CPP/LaserTronGIT/LaserTron/src/ofApp.cpp