LaserTron: WiringPi Class Reference
WiringPi Class Reference
#include <wiringPi.h>
Public Types
enum PinMode { INPUT, OUTPUT }
enum WireSignal { HIGH, LOW }
Static Public Member Functions
static void pinMode (int pin, PinMode mode)
static WireSignal digitalRead (int pin)
static void closePin (int pin)
static void clear ()
Static Public Attributes
static vector< GPIO_Port > OpenGPIO = vector<GPIO_Port>()
Static Private Member Functions
static bool IsPinOpen (int pin)
static GPIO_Port PortByID (int pin)
Detailed Description
Definition at line 51 of file wiringPi.h.
Member Enumeration Documentation
PinMode
enum WiringPi::PinMode
Enumerator
INPUT
OUTPUT
Definition at line 56 of file wiringPi.h.
WireSignal
enum WiringPi::WireSignal
Enumerator
HIGH
LOW
Definition at line 57 of file wiringPi.h.
Member Function Documentation
clear()
void WiringPi::clear () static
Definition at line 55 of file wiringPi.cpp.
References OpenGPIO.
Referenced by ofApp::exit().
closePin()
void WiringPi::closePin (int pin) static
Definition at line 50 of file wiringPi.cpp.
References PortByID().
digitalRead()
WiringPi::WireSignal WiringPi::digitalRead (int pin) static
Definition at line 26 of file wiringPi.cpp.
References PortByID().
Referenced by Player::ProcessInput(), and ofApp::update().
IsPinOpen()
bool WiringPi::IsPinOpen (int pin) static private
Definition at line 45 of file wiringPi.cpp.
References PortByID(), and GPIO_Port::PortID.
Referenced by pinMode().
pinMode()
void WiringPi::pinMode (int pin, PinMode mode) static
Definition at line 5 of file wiringPi.cpp.
References GPIO_Port::DirectionPath, IsPinOpen(), OpenGPIO, and PortByID().
Referenced by Player::Player(), and ofApp::setup().
PortByID()
GPIO_Port WiringPi::PortByID (int pin) static private
Definition at line 35 of file wiringPi.cpp.
References OpenGPIO.
Referenced by closePin(), digitalRead(), IsPinOpen(), and pinMode().
Member Data Documentation
OpenGPIO
vector< GPIO_Port > WiringPi::OpenGPIO = vector<GPIO_Port>() static
Definition at line 64 of file wiringPi.h.
Referenced by clear(), pinMode(), and PortByID().
The documentation for this class was generated from the following files:
D:/PROG/CPP/LaserTronGIT/LaserTron/src/wiringPi.h
D:/PROG/CPP/LaserTronGIT/LaserTron/src/wiringPi.cpp