LaserTron: InputHandler Class Reference
InputHandler Class Reference
#include <SoundThread.h>
Public Member Functions
float GetData ()
Private Member Functions
void audioIn (ofSoundBuffer &buffer) override
void SwapBuffer ()
Private Attributes
float data [2]
int writeBufferIdx
int readBufferIdx
std::mutex _mutex
float Data
float time = 0
int Amplitude = 50
float speed = 0.02
Detailed Description
Definition at line 6 of file SoundThread.h.
Member Function Documentation
audioIn()
void InputHandler::audioIn (ofSoundBuffer & buffer) inline override private
Definition at line 25 of file SoundThread.h.
References data, SwapBuffer(), and writeBufferIdx.
GetData()
float InputHandler::GetData () inline
Definition at line 11 of file SoundThread.h.
Referenced by SoundThread::GetData().
SwapBuffer()
void InputHandler::SwapBuffer () inline private
Definition at line 31 of file SoundThread.h.
References _mutex, readBufferIdx, and writeBufferIdx.
Referenced by audioIn().
Member Data Documentation
_mutex
std::mutex InputHandler::_mutex mutable private
Definition at line 41 of file SoundThread.h.
Referenced by SwapBuffer().
Amplitude
int InputHandler::Amplitude = 50 private
Definition at line 45 of file SoundThread.h.
data
float InputHandler::data[2] private
Definition at line 38 of file SoundThread.h.
Referenced by audioIn().
Data
float InputHandler::Data private
Definition at line 43 of file SoundThread.h.
readBufferIdx
int InputHandler::readBufferIdx private
Definition at line 40 of file SoundThread.h.
Referenced by SwapBuffer().
speed
float InputHandler::speed = 0.02 private
Definition at line 46 of file SoundThread.h.
time
float InputHandler::time = 0 private
Definition at line 44 of file SoundThread.h.
writeBufferIdx
int InputHandler::writeBufferIdx private
Definition at line 39 of file SoundThread.h.
Referenced by audioIn(), and SwapBuffer().
The documentation for this class was generated from the following file:
D:/PROG/CPP/LaserTronGIT/LaserTron/src/SoundThread.h