LaserTron: GameMap Class Reference
GameMap Class Reference
#include <GameMap.h>
Public Member Functions
GameMap (const vector< Player *> &players)
~GameMap ()
int CheckForCollision ()
todo refactor loops
void Update (ofxIlda::Frame *frame, float soundShift)
void RespawnBike (int idx)
void Reset ()
Private Member Functions
int GetSpawnPointIdx ()
void KillBike (int idx)
Private Attributes
vector< Bike * > Bikes
List of the bikes on the map.
vector< BikeWall * > Walls
List of the walls on the map.
vector< Player * > Players
List of the players currently playing.
ofVec2f SpawnPoints [4] = { ofVec2f(0.05, 0.05), ofVec2f(0.05, 0.95), ofVec2f(0.95, 0.95), ofVec2f(0.95, 0.05) }
List of the coordinates of possible spawn point.
int LiveBikes = 0
The number of bikes alive on the map.
ofVec2f Size
UNUSED.
bool bRequiresManualReset = false
UNUSED.
Detailed Description
Class representing the playfield. Responsible for updating the state of the map.
Definition at line 16 of file GameMap.h.
Constructor & Destructor Documentation
GameMap()
GameMap::GameMap (const vector< Player *> & players)
Creates a new map for the players specified by the params
Parameters
players The list players based on which the map is initialized
Definition at line 3 of file GameMap.cpp.
References BikeWall::BikeIdx, Bikes, GetSpawnPointIdx(), Players, SpawnPoints, and Walls.
~GameMap()
GameMap::~GameMap ()
Definition at line 20 of file GameMap.cpp.
Member Function Documentation
CheckForCollision()
int GameMap::CheckForCollision ()
todo refactor loops
Checks the map to detect collisions Kills any bike colliding with a wall, or the edge of the map, or any two bikes colliding with each other
Returns
The number of bikes still alive after the collisions
Definition at line 24 of file GameMap.cpp.
References Bikes, KillBike(), LiveBikes, and Walls.
Referenced by GameThread::Update().
GetSpawnPointIdx()
int GameMap::GetSpawnPointIdx () private
Returns a spawn point on the map. Tries return a point which is furthest from any living bike on the map
Returns
The index of the selected spawn point
Definition at line 87 of file GameMap.cpp.
References Bikes, LiveBikes, and SpawnPoints.
Referenced by GameMap(), Reset(), and RespawnBike().
KillBike()
void GameMap::KillBike (int idx) private
Kills the bike with the specified idx.
Parameters
idx The idx of the bike to kill
Definition at line 110 of file GameMap.cpp.
References Bikes, and LiveBikes.
Referenced by CheckForCollision().
Reset()
void GameMap::Reset ()
Resets the map. Respawns the bikes.
Definition at line 78 of file GameMap.cpp.
References Bikes, GetSpawnPointIdx(), and SpawnPoints.
Referenced by GameThread::Restart().
RespawnBike()
void GameMap::RespawnBike (int idx)
Respawns the bike on the given spawn point
Parameters
idx The idx of the spawn point to respawn to
Definition at line 71 of file GameMap.cpp.
References Bikes, GetSpawnPointIdx(), LiveBikes, and SpawnPoints.
Referenced by Player::ProcessInput().
Update()
void GameMap::Update (ofxIlda::Frame * frame, float soundShift)
Updates the elements on the map
Parameters
frame The Ilda queue to draw any map elements to
soundShift Value produced by the sound engine to modulate the graphics
Definition at line 59 of file GameMap.cpp.
References Bikes, and Walls.
Referenced by GameThread::Update().
Member Data Documentation
Bikes
vector<Bike*> GameMap::Bikes private
List of the bikes on the map.
Definition at line 64 of file GameMap.h.
Referenced by CheckForCollision(), GameMap(), GetSpawnPointIdx(), KillBike(), Reset(), RespawnBike(), and Update().
bRequiresManualReset
bool GameMap::bRequiresManualReset = false private
UNUSED.
Definition at line 71 of file GameMap.h.
LiveBikes
int GameMap::LiveBikes = 0 private
The number of bikes alive on the map.
Definition at line 69 of file GameMap.h.
Referenced by CheckForCollision(), GetSpawnPointIdx(), KillBike(), and RespawnBike().
Players
vector<Player*> GameMap::Players private
List of the players currently playing.
Definition at line 66 of file GameMap.h.
Referenced by GameMap().
Size
ofVec2f GameMap::Size private
UNUSED.
Definition at line 70 of file GameMap.h.
SpawnPoints
ofVec2f GameMap::SpawnPoints[4] = { ofVec2f(0.05, 0.05), ofVec2f(0.05, 0.95), ofVec2f(0.95, 0.95), ofVec2f(0.95, 0.05) } private
List of the coordinates of possible spawn point.
Definition at line 67 of file GameMap.h.
Referenced by GameMap(), GetSpawnPointIdx(), Reset(), and RespawnBike().
Walls
vector<BikeWall*> GameMap::Walls private
List of the walls on the map.
Definition at line 65 of file GameMap.h.
Referenced by CheckForCollision(), GameMap(), and Update().
The documentation for this class was generated from the following files:
D:/PROG/CPP/LaserTronGIT/LaserTron/src/GameMap.h
D:/PROG/CPP/LaserTronGIT/LaserTron/src/GameMap.cpp